<?php
/**
 * article.php — purAIkerto articles endpoint
 *
 * GET /api/article.php             → list all articles (summary only)
 * GET /api/article.php?id=...      → get full article by id
 * GET /api/article.php?slug=...    → get full article by slug
 *
 * Articles live as JSON files in /articles/<id>.json, generated by
 * src/article.py (long-form content, not bound to 24h rolling).
 */

declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: public, max-age=300');
header('X-Content-Type-Options: nosniff');

$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if ($origin && preg_match('#^https://([a-z0-9-]+\.)?puraikerto\.my\.id$#i', $origin)) {
    header("Access-Control-Allow-Origin: $origin");
    header('Vary: Origin');
}

$articles_dir = dirname(__DIR__) . '/articles';
$id = isset($_GET['id']) ? preg_replace('/[^a-z0-9-]/i', '', (string) $_GET['id']) : '';
$slug = isset($_GET['slug']) ? preg_replace('/[^a-z0-9-]/i', '', (string) $_GET['slug']) : '';

// specific article by id or slug
if ($id || $slug) {
    if (!is_dir($articles_dir)) {
        http_response_code(404);
        echo json_encode(['error' => 'no articles yet'], JSON_UNESCAPED_UNICODE);
        exit;
    }
    foreach (glob($articles_dir . '/*.json') as $path) {
        $a = json_decode((string) file_get_contents($path), true);
        if (!is_array($a)) continue;
        if (($id && ($a['id'] ?? '') === $id) || ($slug && ($a['slug'] ?? '') === $slug)) {
            echo json_encode($a, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
            exit;
        }
    }
    http_response_code(404);
    echo json_encode(['error' => 'article not found'], JSON_UNESCAPED_UNICODE);
    exit;
}

// list all articles (summary only, newest first)
if (!is_dir($articles_dir)) {
    echo json_encode(['articles' => []], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
    exit;
}

$files = glob($articles_dir . '/*.json');
rsort($files); // newest first by filename (uuid prefix is random; mtime would be more accurate, but rsort by name is fine)

$out = [];
foreach ($files as $path) {
    $a = json_decode((string) file_get_contents($path), true);
    if (!is_array($a)) continue;
    $out[] = [
        'id' => $a['id'] ?? '',
        'title' => $a['title'] ?? '',
        'title_id' => $a['title_id'] ?? '',
        'slug' => $a['slug'] ?? '',
        'summary' => $a['summary'] ?? '',
        'summary_id' => $a['summary_id'] ?? '',
        'topic' => $a['topic'] ?? '',
        'grid_origin' => $a['grid_origin'] ?? '',
        'confidence' => $a['confidence'] ?? 0,
        'read_minutes' => $a['read_minutes'] ?? 3,
        'created_at' => $a['created_at'] ?? '',
        'updated_at' => $a['updated_at'] ?? '',
    ];
}

usort($out, function($a, $b) {
    return strcmp($b['created_at'] ?? '', $a['created_at'] ?? '');
});

echo json_encode(['articles' => $out, 'count' => count($out)], JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
