<?php
/**
 * reason.php — purAIkerto reasoning trace endpoint
 *
 * GET /api/reason.php?title=...&url=...  → generate fresh trace for an item
 * GET /api/reason.php?from=cache&idx=N  → return trace N from cache_reason.json
 *
 * Why this exists: the "Holds a plan" + "Fact check themselves" criteria of
 * MiniMaxathon Track 1 is satisfied by exposing the agent's plan + steps to
 * the user, not by a black-box answer.
 *
 * Caching:
 *   - Traces are generated by src/reason.py and stored in cache_reason.json
 *   - If the requested item's URL is in cache → return cached trace
 *   - If not → call M3 synchronously (slower, but always works for demo)
 *
 * Rate-limiting (security):
 *   - Path 2 (generate-on-the-fly) is gated by:
 *     (a) URL must exist in current cache_feed.json (else 404)
 *     (b) per-IP file-based counter: 10 requests / 60s
 *   - This prevents random URLs from burning M3 quota via shell_exec
 *
 * Error handling:
 *   - Internal failures log to error_log() but the client only sees a
 *     generic message — we never leak stack traces, paths, or key material.
 */

declare(strict_types=1);

set_time_limit(0); // reason.py can take 60s+ under M3 rate-limit retries
ini_set('max_execution_time', '0');

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: public, max-age=600'); // 10 min
header('X-Content-Type-Options: nosniff');

$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if ($origin && preg_match('#^https://([a-z0-9-]+\.)?puraikerto\.my\.id$#i', $origin)) {
    header("Access-Control-Allow-Origin: $origin");
    header('Vary: Origin');
}

// ---- inputs ----
$cache_path = __DIR__ . '/cache_reason.json';
$feed_path  = __DIR__ . '/cache_feed.json';

$title = isset($_GET['title']) ? trim((string) $_GET['title']) : '';
$url   = isset($_GET['url'])   ? trim((string) $_GET['url'])   : '';

// ---- helper: gather all known URLs from the live feed cache ----
function puraikerto_known_urls(string $feed_path): array {
    if (!is_file($feed_path)) return [];
    $raw = @file_get_contents($feed_path);
    if ($raw === false) return [];
    $d = json_decode($raw, true);
    if (!is_array($d) || empty($d['grids'])) return [];
    $set = [];
    foreach ($d['grids'] as $items) {
        if (!is_array($items)) continue;
        foreach ($items as $it) {
            if (!empty($it['url'])) $set[$it['url']] = true;
        }
    }
    return array_keys($set);
}

// ---- helper: per-IP rate limiter (file-based) ----
function puraikerto_rate_limit_check(string $ip, int $max = 10, int $window_s = 60): bool {
    // 10 req / 60s per IP. State lives in /tmp; ephemeral by design.
    $dir = sys_get_temp_dir() . '/puraikerto_rl';
    if (!is_dir($dir)) {
        @mkdir($dir, 0700, true);
    }
    $key = preg_replace('/[^a-z0-9]/i', '', $ip) ?: 'anon';
    $bucket_file = $dir . '/rl_' . $key . '.json';
    $now = time();
    $state = ['start' => $now, 'count' => 0];
    if (is_file($bucket_file)) {
        $raw = @file_get_contents($bucket_file);
        $parsed = $raw !== false ? json_decode($raw, true) : null;
        if (is_array($parsed) && isset($parsed['start'], $parsed['count'])) {
            $state = $parsed;
        }
    }
    if (($now - (int)$state['start']) >= $window_s) {
        $state = ['start' => $now, 'count' => 0];
    }
    $state['count'] = (int)$state['count'] + 1;
    @file_put_contents($bucket_file, json_encode($state), LOCK_EX);
    return $state['count'] <= $max;
}

// ---- path 1: cache lookup by URL ----
if ($url && is_file($cache_path)) {
    $raw = @file_get_contents($cache_path);
    if ($raw !== false) {
        $cache = json_decode($raw, true);
        if (is_array($cache) && !empty($cache['traces'])) {
            foreach ($cache['traces'] as $t) {
                if (isset($t['item_url']) && $t['item_url'] === $url) {
                    echo json_encode($t, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
                    exit;
                }
            }
        }
    }
}

// ---- need title+url to proceed ----
if (!$title || !$url) {
    http_response_code(400);
    echo json_encode(['error' => 'missing title or url param'], JSON_UNESCAPED_UNICODE);
    exit;
}

// ---- path 2: generate on the fly. Gated by per-IP rate limit only. ----

// gate: per-IP rate limit
$ip = $_SERVER['REMOTE_ADDR'] ?? '0.0.0.0';
if (!puraikerto_rate_limit_check($ip)) {
    http_response_code(429);
    header('Retry-After: 60');
    echo json_encode(['error' => 'rate limit exceeded — slow down and try again in a minute'], JSON_UNESCAPED_UNICODE);
    exit;
}

// ---- resolve venv python ----
$venv_python = getenv('PURAIKERTO_VENV_PYTHON');
if (!$venv_python) {
    $venv_python = '/home/wijang/www/puraikerto/src/.venv/bin/python3';  // VPS path
}
if (!is_file($venv_python)) {
    // local/dev fallback
    $venv_python = __DIR__ . '/../src/.venv/bin/python3';
}

$env_path = getenv('PURAIKERTO_ENV_PATH') ?: '/home/wijang/www/puraikerto/.env';  // web-readable copy

$src_dir = realpath(__DIR__ . '/../src');
if ($src_dir === false) {
    http_response_code(500);
    error_log('[puraikerto reason] src dir not found');
    echo json_encode(['error' => 'internal error'], JSON_UNESCAPED_UNICODE);
    exit;
}

// resolve GMI_API_KEY — read from .env (PHP-FPM cannot rely on shell env)
$gmi_key = '';
if (is_file($env_path)) {
    $lines = @file($env_path);
    if ($lines) {
        foreach ($lines as $ln) {
            $ln = trim($ln);
            if (str_starts_with($ln, 'GMI_API_KEY=')) {
                $gmi_key = trim(substr($ln, strlen('GMI_API_KEY=')), '"\'');
                break;
            }
        }
    }
}
if ($gmi_key === '' && getenv('GMI_API_KEY')) {
    $gmi_key = getenv('GMI_API_KEY');
}

$item = json_encode([
    'title'   => $title,
    'url'     => $url,
    'summary' => $_GET['summary'] ?? '',
    'source'  => $_GET['source']  ?? '',
], JSON_UNESCAPED_UNICODE);

// pass key explicitly so reason.py never needs to read .env itself
$cmd = sprintf(
    'cd %s && GMI_API_KEY=%s %s reason.py --item %s 2>&1',
    escapeshellarg($src_dir),
    escapeshellarg($gmi_key),
    escapeshellarg($venv_python),
    escapeshellarg($item)
);

// run once — reason.py itself retries M3 on 429/5xx (gmi_client has 4 retries)
$output = shell_exec($cmd);
if ($output === null) {
    http_response_code(200);
    error_log('[puraikerto reason] shell_exec returned null for url=' . $url);
    echo json_encode([
        'item_title' => $title,
        'item_url'   => $url,
        'plan'       => ['Cek ketersediaan artikel di sumber.', 'Verifikasi klaim utama.', 'Konklusi.'],
        'steps'      => [],
        'sources'    => [],
        'confidence' => 0.0,
        'summary'    => 'Maaf, agent sedang tidak bisa memproses artikel ini (koneksi ke model terputus). Coba beberapa saat lagi.',
        'error'      => 'agent_unavailable',
    ], JSON_UNESCAPED_UNICODE);
    exit;
}

// last JSON-looking line wins
$lines = explode("\n", trim($output));
$json_line = '';
for ($i = count($lines) - 1; $i >= 0; $i--) {
    if (str_starts_with(trim($lines[$i]), '{')) {
        $json_line = $lines[$i];
        break;
    }
}
if ($json_line) {
    // reason.py may return a trace that itself carries an `error` field
    // (M3 call failed). Pass it through with 200 so the panel still renders.
    echo $json_line;
    exit;
}

// no JSON produced — log full output server-side, return a graceful trace
error_log('[puraikerto reason] no trace produced for url=' . $url . ' output=' . substr($output, 0, 2000));
http_response_code(200);
echo json_encode([
    'item_title' => $title,
    'item_url'   => $url,
    'plan'       => ['Cek ketersediaan artikel di sumber.', 'Verifikasi klaim utama.', 'Konklusi.'],
    'steps'      => [],
    'sources'    => [],
    'confidence' => 0.0,
    'summary'    => 'Agent gagal menghasilkan trace untuk artikel ini. Mungkin model sedang sibuk — coba lagi nanti.',
    'error'      => 'no_trace',
], JSON_UNESCAPED_UNICODE);
