<?php
/**
 * reason.php — purAIkerto reasoning trace endpoint
 *
 * GET /api/reason.php?title=...&url=...  → generate fresh trace for an item
 * GET /api/reason.php?from=cache&idx=N  → return trace N from cache_reason.json
 *
 * Why this exists: the "Holds a plan" + "Fact check themselves" criteria of
 * MiniMaxathon Track 1 is satisfied by exposing the agent's plan + steps to
 * the user, not by a black-box answer.
 *
 * Caching:
 *   - Traces are generated by src/reason.py and stored in cache_reason.json
 *   - If the requested item's URL is in cache → return cached trace
 *   - If not → call M3 synchronously (slower, but always works for demo)
 *
 * NOTE: synchronous M3 calls are rate-limited; for production this should be
 * a job queue. For 14-day contest, sync is fine.
 */

declare(strict_types=1);

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: public, max-age=600'); // 10 min
header('X-Content-Type-Options: nosniff');

$origin = $_SERVER['HTTP_ORIGIN'] ?? '';
if ($origin && preg_match('#^https://([a-z0-9-]+\.)?puraikerto\.my\.id$#i', $origin)) {
    header("Access-Control-Allow-Origin: $origin");
    header('Vary: Origin');
}

$cache_path = __DIR__ . '/cache_reason.json';
$title = isset($_GET['title']) ? trim((string) $_GET['title']) : '';
$url = isset($_GET['url']) ? trim((string) $_GET['url']) : '';

// path 1: look up by URL in cache
if ($url && is_file($cache_path)) {
    $raw = file_get_contents($cache_path);
    if ($raw !== false) {
        $cache = json_decode($raw, true);
        if (is_array($cache) && !empty($cache['traces'])) {
            foreach ($cache['traces'] as $t) {
                if (isset($t['item_url']) && $t['item_url'] === $url) {
                    echo json_encode($t, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);
                    exit;
                }
            }
        }
    }
}

// path 2: generate on the fly via shell to src/reason.py
if ($title && $url) {
    $item = json_encode([
        'title' => $title,
        'url' => $url,
        'summary' => $_GET['summary'] ?? '',
        'source' => $_GET['source'] ?? '',
    ], JSON_UNESCAPED_UNICODE);

    $venv_python = '/home/wijang/.hermes/.venv/bin/python3';
    if (!is_file($venv_python)) {
        $venv_python = '/usr/bin/python3';
    }
    $src_dir = realpath(__DIR__ . '/../src');
    if ($src_dir === false) {
        http_response_code(500);
        echo json_encode(['error' => 'src dir not found'], JSON_UNESCAPED_UNICODE);
        exit;
    }

    $cmd = sprintf(
        'cd %s && GMI_API_KEY=$(grep ^GMI_API_KEY= ~/.hermes/.env | cut -d= -f2-) %s reason.py --item %s 2>&1',
        escapeshellarg($src_dir),
        escapeshellarg($venv_python),
        escapeshellarg($item)
    );
    $output = shell_exec($cmd);
    if ($output === null) {
        http_response_code(500);
        echo json_encode(['error' => 'reason.py exec failed'], JSON_UNESCAPED_UNICODE);
        exit;
    }

    // last JSON-looking line wins (curate.py may log to stdout)
    $lines = explode("\n", trim($output));
    $json_line = '';
    for ($i = count($lines) - 1; $i >= 0; $i--) {
        if (str_starts_with(trim($lines[$i]), '{')) {
            $json_line = $lines[$i];
            break;
        }
    }
    if ($json_line) {
        echo $json_line;
    } else {
        http_response_code(500);
        echo json_encode(['error' => 'no trace produced', 'log' => $output], JSON_UNESCAPED_UNICODE);
    }
    exit;
}

http_response_code(400);
echo json_encode(['error' => 'missing title or url param'], JSON_UNESCAPED_UNICODE);
